name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build YimLauncher.sln --configuration Release --output ./output

      - name: Publish
        run: dotnet publish ./output/YimLauncher/YimLauncher.csproj --configuration Release --output ./published --runtime win-x64 --single-file
